/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 businessMan.gltf
Author: art.piskov (https://sketchfab.com/art.piskov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/buisness-man-with-talking-animation-3fe2b15e0c884b66b987f6f48e420f56
Title: Buisness man (With talking animation)
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import SpeechRecognition , { useSpeechRecognition } from 'react-speech-recognition'
import axios from 'axios'

export default function Model(props) {
  const { transcript, resetTranscript } = useSpeechRecognition()
  const [talk, setTalk] = useState(true)
  const [listen, setListen] = useState(false)
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/businessMan.gltf')
  const { actions } = useAnimations(animations, group)

  function handleListen() {
    if (listen) {
        console.log("Transcript: ", transcript)
        if (transcript != ""){
          axios.post('http://localhost:4000/text-input', {message: transcript})
          .then(response => props.setSpeechText(response.data))
        }
        actions.CC3_Base_Plus_TempMotion.halt()
        SpeechRecognition.stopListening()
        resetTranscript()
        setListen(false)
    } else {
      console.log("play")
      actions.CC3_Base_Plus_TempMotion.stop()
      actions.CC3_Base_Plus_TempMotion.play()
        SpeechRecognition.startListening()
        setListen(true)
    }
  }


  
  return (
    <group ref={group} {...props} dispose={null} onClick={(e)=> {
      handleListen()
      }}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[1.57, 0, 0]} scale={0.93}>
          <group name="2661a2afc9dd44dda6abf07a3bbb5431fbx" rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="Object_8" />
                  <group name="Object_15" />
                  <group name="Object_20" />
                  <group name="Object_23" />
                  <group name="Object_26" />
                  <group name="Object_29" />
                  <group name="Object_31" />
                  <group name="Object_33" />
                  <group name="Object_35" />
                  <group name="CC_Base_Tongue" />
                  <group name="CC_Base_Body" />
                  <group name="CC_Base_Eye" />
                  <group name="CC_Base_Teeth" />
                  <group name="CC_Base_EyeOcclusion" />
                  <group name="CC_Base_TearLine" />
                  <group name="Boxers" />
                  <group name="Slacks" />
                  <group name="Business_Shirt" />
                  <group name="Leather_shoes" />
                  <group name="RL_HairMesh" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Std_Tongue} skeleton={nodes.Object_7.skeleton} morphTargetDictionary={nodes.Object_7.morphTargetDictionary} morphTargetInfluences={nodes.Object_7.morphTargetInfluences} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Std_Skin_Head} skeleton={nodes.Object_9.skeleton} morphTargetDictionary={nodes.Object_9.morphTargetDictionary} morphTargetInfluences={nodes.Object_9.morphTargetInfluences} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Std_Skin_Body} skeleton={nodes.Object_10.skeleton} morphTargetDictionary={nodes.Object_10.morphTargetDictionary} morphTargetInfluences={nodes.Object_10.morphTargetInfluences} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Std_Skin_Arm} skeleton={nodes.Object_11.skeleton} morphTargetDictionary={nodes.Object_11.morphTargetDictionary} morphTargetInfluences={nodes.Object_11.morphTargetInfluences} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Std_Skin_Leg} skeleton={nodes.Object_12.skeleton} morphTargetDictionary={nodes.Object_12.morphTargetDictionary} morphTargetInfluences={nodes.Object_12.morphTargetInfluences} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Std_Nails} skeleton={nodes.Object_13.skeleton} morphTargetDictionary={nodes.Object_13.morphTargetDictionary} morphTargetInfluences={nodes.Object_13.morphTargetInfluences} />
                  <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Std_Eyelash} skeleton={nodes.Object_14.skeleton} morphTargetDictionary={nodes.Object_14.morphTargetDictionary} morphTargetInfluences={nodes.Object_14.morphTargetInfluences} />
                  <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Std_Eye_Occlusion_R} skeleton={nodes.Object_24.skeleton} morphTargetDictionary={nodes.Object_24.morphTargetDictionary} morphTargetInfluences={nodes.Object_24.morphTargetInfluences} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Std_Eye_Occlusion_L} skeleton={nodes.Object_25.skeleton} morphTargetDictionary={nodes.Object_25.morphTargetDictionary} morphTargetInfluences={nodes.Object_25.morphTargetInfluences} />
                  <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Std_Tearline_R} skeleton={nodes.Object_27.skeleton} morphTargetDictionary={nodes.Object_27.morphTargetDictionary} morphTargetInfluences={nodes.Object_27.morphTargetInfluences} />
                  <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Std_Tearline_L} skeleton={nodes.Object_28.skeleton} morphTargetDictionary={nodes.Object_28.morphTargetDictionary} morphTargetInfluences={nodes.Object_28.morphTargetInfluences} />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Std_Eye_R} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Std_Cornea_R} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Std_Eye_L} skeleton={nodes.Object_18.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Std_Cornea_L} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Std_Upper_Teeth} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Std_Lower_Teeth} skeleton={nodes.Object_22.skeleton} />
                  <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Slacks} skeleton={nodes.Object_30.skeleton} />
                  <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Business_Shirt} skeleton={nodes.Object_32.skeleton} />
                  <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Leather_shoes} skeleton={nodes.Object_34.skeleton} />
                  <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Classic_Taper_Scalp} skeleton={nodes.Object_36.skeleton} />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Classic_Taper} skeleton={nodes.Object_37.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/businessMan.gltf')
