/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 person.gltf
Author: arunkumar2057 (https://sketchfab.com/arunkumar2057)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/amp-suite-from-avatar-46658c9605584d8297fc79ca4f802dc5
Title: AMP suite from Avatar
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  
  const { nodes, materials } = useGLTF('/person.gltf')
  return (
    <group {...props} dispose={null} scale={1/40} position={[0,-3,0]}>
      <mesh geometry={nodes.hands_legs_hands_legs1_0.geometry} material={materials.hands_legs1} />
      <mesh geometry={nodes.body_knife_body_knife1_0.geometry} material={materials.body_knife1} />
      <mesh geometry={nodes.body_knife_body_knife1_0_1.geometry} material={materials.body_knife1} />
      <mesh geometry={nodes.body_knife_body_knife1_0_2.geometry} material={materials.body_knife1} />
      <mesh geometry={nodes.riffle_riffle1_0.geometry} material={materials.riffle1} />
    </group>
  )
}

useGLTF.preload('/person.gltf')
